name: Astra DB Cleanup
description: Delete a database in Astra DB

inputs:
  astra-token:
    required: true
    description: "Astra DB application token"
  db-name:
    required: true
    description: "Astra DB database name"
  env:
    required: true
    description: "Astra DB env"
runs:
  using: "composite"
  steps:
    - name: Delete database
      shell: bash
      env:
        TERM: linux
      run: |
        (curl -Ls "https://dtsx.io/get-astra-cli" | bash) || true
        /home/runner/.astra/cli/astra db delete "${{ inputs.db-name }}" --token ${{ inputs.astra-token }} --env "${{ inputs.env }}" --async
