name: 'Generate Slack report'
description: 'Generate a report for Slack'
inputs:
  output-file:
    required: true
    description: 'File to write the report to'
    default: 'slack-report.json'
  type:
    required: true
    description: 'Type of the report'
  outcome:
    required: true
    description: 'Outcome of the test run'
  commit-url:
    required: true
    description: 'Github commit url'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      if [ "${{ inputs.outcome }}" != "success" ]; then
        summary="Other tests: FAILED ❌"
      else
        summary="Other tests: PASSED ✅"
      fi
      echo -n '{"content": "' > ${{ inputs.output-file }}
      echo -n "$summary\n" >> ${{ inputs.output-file }}
      if [ -f "ragstack-e2e-tests/generated-compatibility-matrix.txt" ]; then
        {
          cat ragstack-e2e-tests/generated-compatibility-matrix.txt | sed 's/"/\\"/g' | while IFS= read -r line; do
            echo -n "$line\n"
          done
        } >> ${{ inputs.output-file }}
        echo "Compatibility matrix report found"
      else
        echo "Compatibility matrix report NOT found"
        pwd
        ls -la .
        ls -la ragstack-e2e-tests || echo "ragstack-e2e-tests dir not found"
      fi
      echo "\",\"commit\":\"${{ inputs.commit-url }}\",\"url\":\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\",\"type\":\"${{ inputs.type }}\"}" >> ${{ inputs.output-file }}
      echo "Slack report generated to ${{ inputs.output-file }}"
      cat ${{ inputs.output-file }}
