name: 'Generate Slack report'
description: 'Generate a report for Slack'
inputs:
  from-report-file:
    required: true
    description: 'File to read the report from'
  output-file:
    required: true
    description: 'File to write the report to'
    default: 'slack-report.json'
  type:
    required: true
    description: 'Type of the report'
  outcome:
    required: true
    description: 'Outcome of the test run'
  commit-url:
    required: true
    description: 'Github commit url'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      from_file=${{ inputs.from-report-file }}
      if [ -f "$from_file" ]; then
        echo "Report found"
      else
        echo "Report NOT found"
        pwd
        ls -la .
        touch $from_file 
      fi
      if [ "${{ inputs.outcome }}" != "success" ]; then
        summary="FAILED ❌"
      else
        summary="PASSED ✅"
      fi
      jq \
        --arg content "$(cat $from_file)" \
        --arg summary "$summary" \
        --arg commit "${{ inputs.commit-url }}" \
        --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
        --arg type "${{ inputs.type }}" \
        -n '{"content": $content, "summary": $summary, "commit": $commit, "url": $url, "type": $type}'  > ${{ inputs.output-file }}
      echo "Slack report generated to ${{ inputs.output-file }}"
      cat ${{ inputs.output-file }}
