name: 'Generate Slack report'
description: 'Generate a report for Slack'
inputs:
  from-report-file:
    required: true
    description: 'File to read the report from'
  output-file:
    required: true
    description: 'File to write the report to'
    default: 'slack-report.json'
  type:
    required: true
    description: 'Type of the report'
  outcome:
    required: true
    description: 'Outcome of the test run'
  commit-url:
    required: true
    description: 'Github commit url'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      
      echo -n '{"content": "' > ${{ inputs.output-file }}
      if [ -f "${{ inputs.from-report-file }}" ]; then
        echo "Report found"
        cat ${{ inputs.from-report-file }}
        sed 's/"/\\"/g' ${{ inputs.from-report-file }} >> ${{ inputs.output-file }}
      else
        echo "Report NOT found"
        pwd
        ls -la .
      fi
      if [ "${{ inputs.outcome }}" != "success" ]; then
        summary="FAILED ❌"
      else
        summary="PASSED ✅"
      fi
      echo "\",\"summary\":\"$summary\",\"commit\":\"${{ inputs.commit-url }}\",\"url\":\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\",\"type\":\"${{ inputs.type }}\"}" >> ${{ inputs.output-file }}
      echo "Slack report generated to ${{ inputs.output-file }}"
      cat ${{ inputs.output-file }}
