# https://github.com/dorny/paths-filter
e2e_tests:
  - added|deleted|modified: 'ragstack-e2e-tests/**'
  - 'pyproject.toml'
notebooks:
  - added|deleted|modified: 'examples/notebooks/**'
  - 'pyproject.toml'
