# https://github.com/dorny/paths-filter
e2e_tests:
  - added|deleted|modified: "ragstack-e2e-tests/**"
  - "pyproject.toml"
  - "./.github/actions/**"
  - "./.github/workflows/ci-e2e-tests.yml"
  - "./.github/workflows/_run_e2e_tests.yml"
notebooks:
  - added|deleted|modified: "examples/notebooks/**"
  - "pyproject.toml"
  - "tox.ini"
  - "./.github/actions/**"
  - "./.github/workflows/ci-e2e-tests.yml"
  - "./.github/workflows/_run_e2e_tests.yml"
