# https://github.com/dorny/paths-filter
e2e_tests:
  - "libs/e2e-tests/**"
  - "pyproject.toml"
  - "libs/llamaindex/pyproject.toml"
  - "libs/langchain/pyproject.toml"
  - "libs/tests-utils/pyproject.toml"
  - "./.github/actions/**"
  - "./.github/workflows/ci-e2e-tests.yml"
  - "./.github/workflows/_run_e2e_tests.yml"
notebooks:
  - added|deleted|modified: "examples/notebooks/**"
  - "pyproject.toml"
  - "tox.ini"
  - "./.github/actions/**"
  - "./.github/workflows/ci-e2e-tests.yml"
  - "./.github/workflows/_run_e2e_tests.yml"
integration_tests:
  - "libs/colbert/**"
  - "libs/llamaindex/**"
  - "libs/langchain/**"
  - "./.github/actions/**"
  - "./.github/workflows/ci-unit-tests.yml"
docker_examples:
  - "docker/examples/**"
  - "./.github/actions/**"
  - "./.github/workflows/ci-unit-tests.yml"
libs_colbert:
  - "libs/colbert/**"
libs_langchain:
  - "libs/langchain/**"
  - "libs/colbert/**"
libs_llamaindex:
  - "libs/llamaindex/**"
  - "libs/colbert/**"
libs_knowledge_graph:
  - "libs/knowledge-graph/**"
libs_knowledge_store:
  - "libs/knowledge-graph/**"
