= Knowledge Graph RAG

Knowledge Graph RAG is a RAGStack package that provides a graph-based representation of information. It is designed to store and retrieve information in a way that is more efficient and accurate than vector-based similarity search.

A knowledge graph represents entities (real world objects, like "Marie Callendar" or "maize") as **nodes**. Nodes are connected by **edges** indicating relationships between them. For example, "Marie Callendar" might be connected to "pie" by an edge labeled "makes".

*TL;DR:*

. RAG based on chunking and vector similarity search has some weaknesses.
.. Similarity search looks for information most similar to the question. This makes is harder to answer questions with multiple topics.
.. Similarity search limits the number of chunks retrieved. What if there is similar information spread across multiple places? A similarity search must choose between retrieving multiple copies of the information (inefficient), or choosing only one copy (less context).
. Knowledge graphs address these shortcomings. For example, if multiple sources say the same thing, that knowledge is stored as one node instead of disparate chunks.
. From a developer's perspective, a knowledge graph is built into a RAG pipeline similarly to a vector search. The difference is in the underlying data structure and how the information is stored and retrieved.

== The `ragstack-ai-knowledge-graph` package

`ragstack-ai-knowledge-graph` contains the implementation of Knowledge Graph and all required dependencies, including Langchain and the https://cassio.org/frameworks/langchain/about/[cassio] library for integration with Cassandra databases.

To install the package, run:

[source,bash]
====
pip install ragstack-ai-knowledge-graph
====

== How is Knowledge Graph different from RAG?

== Knowledge Graph, RAGStack, and Astra DB

== Advantages of Knowledge Graph on Astra DB