= Introduction to Graph-Based Knowledge Extraction and Traversal

[IMPORTANT]
====
The RAGStack knowledge graph libraries
`ragstack-ai-knowledge-graph` and `ragstack-ai-knowledge-store`
are no longer under development, and have been superseded by the 
https://github.com/datastax/graph-rag[Graph RAG project].

Please visit
https://github.com/datastax/graph-rag[Graph RAG project]
for the latest tools and techniques for working with 
knowledge graphs and graph RAG.

If you have further questions, please contact
https://support.datastax.com/[DataStax Support].

====


A knowledge graph represents information as **nodes**. Nodes are connected by **edges** indicating relationships between them. Each edge includes the source (for example, "Marie Curie" the person), the target ("Nobel Prize" the award) and a type, indicating how the source relates to the target (for example, “won”).


== What's the difference between knowledge graphs and vector similarity search?

Retrieval augmented generation based on chunking and vector similarity search has some weaknesses.

. Similarity search only looks for information most similar to the question. This makes it harder to answer questions with multiple topics, or address cases where less-similar information is still relevant to the question.
. Similarity search limits the number of chunks retrieved. What if there is similar information spread across multiple places? A similarity search must choose between retrieving multiple copies of the information (inefficient), or choosing only one copy (less context).

Knowledge graphs address these shortcomings. For example, if multiple sources have similar information, that knowledge is stored as one node instead of as disparate chunks.

From a developer's perspective, a knowledge graph is built into a RAG pipeline similarly to a vector search. The difference is in the underlying data structure and how the information is stored and retrieved.

For example: consider a tech support system, where you find an article that is similar to your question, and it says. "If you have trouble with step 4, see this article for more information". Even if "more information" is not similar to your original question, it likely provides more information.

The article's "see more information" is an example of an edge in a knowledge graph. The edge connects the initial article to additional information, indicating that the two are related. This relationship would not be captured in a similarity search.

These edges also increase the diversity of results. Within the same tech support system, if you retrieve 100 chunks that are highly similar to the question, you have retrieved 100 chunks that are also highly similar to themselves. Following edges to linked information increases diversity.





