= {graph-store}

{graph-store} is a hybrid vector-and-graph graph store that combines the benefits of vector stores with the context and relationships of related edges between chunks.

See the xref:examples:knowledge-store.adoc[graph store example code] to get started with {graph-store}.

[IMPORTANT]
====
This feature is currently under development and has not been fully tested. It is not supported for use in production environments. Please use this feature in testing and development environments only.
====

== The `ragstack-ai-knowledge-store` library

The `ragstack-ai-knowledge-store` library contains functions for creating a hybrid vector-and-graph knowledge store. This store combines the benefits of vector stores with the context and relationships of a related edges.

To install the package, run:

[source,bash]
----
pip install ragstack-ai-knowledge-store
----

== Coarse-grained knowledge graphs

{graph-store} 

== graph store, RAGStack, and Astra DB

{graph-store} is built on top of RAGStack and Astra DB.




