# Inspired from official Snyk GitHub Action for Python but force usage of Python 3.11
# https://github.com/snyk/actions/blob/master/python/action.yml

name: "Snyk Python"
description: "Check your Python application for vulnerabilties using Snyk"
inputs:
  token:
    required: true
    description: 'Snyk token'
runs:
  using: "docker"
  image: "docker://snyk/snyk:python-3.11"
  env:
    FORCE_COLOR: 2
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: python
    SNYK_TOKEN: "${{ inputs.token }}"
  args:
  - snyk
  - test
  - --severity-threshold=high
  - --json-file-output=snyk-vuln.json
  - --print-deps