= {product} Documentation

++++
<div class="landing-row">
++++

[sidebar.landing-card]
.What is {product}?
****
--
{product} is a curated stack of the best open-source software for easing implementation of the RAG pattern in production-ready applications using {db-serverless} or Apache Cassandra as a vector store.

A single command (`pip install ragstack-ai`) unlocks all the open-source packages required to build production-ready RAG applications with LangChain and the vector-enabled {db-serverless} database.

For each open-source project included in {product}, we select a version lineup and then test the combination for compatibility, performance, and security. Our extensive test suite ensures that {product} components work well together so you can confidently deploy them in production. We also run security scans on all components using industry-standard tools to ensure that you are not exposed to known vulnerabilities.

If you are already using an open-source library that is part of {product} in your project, such as LangChain, it should be easy to switch it to {product} by simply updating the requirements.
--
// [.landing-card-body-icon]
// image::what-is-astra-db.svg[Astra DB card icon,40]
****

++++
</div>
++++

++++
<div class="landing-row">
++++

[sidebar.landing-card]
.Components
****
--
{company} has been busy helping our customers through the pains of RAG implementation, so the {product} components we've selected have withstood production workloads and stringent testing by our engineering teams for performance, compatibility, and security.

* {product} leverages the https://python.langchain.com/docs/get_started/introduction[LangChain] ecosystem and is fully compatible with https://docs.smith.langchain.com/[LangSmith] for monitoring your AI deployments.

* The https://docs.datastax.com/en/astra/astra-db-vector/get-started/quickstart.html[{db-serverless}] database provides the best performance and scalability for RAG applications, in addition to being particularly well-suited to RAG workloads like question answering, semantic search, and semantic caching.
--
// [.landing-card-body-icon]
// image::what-is-astra-db.svg[Astra DB card icon,40]
****

[sidebar.landing-card]
.Why {product}?
****
--
{product} offers solutions for challenges facing developers building RAG applications.

* Productivity -- abstract over the RAG pattern's complexities to keep developers focused on business logic.
* Advanced RAG techniques -- use advanced patterns like RAG fusion and FLARE.
* Future-proof -- as new techniques are discovered, {product} offers enterprise users a predictable upgrade path to always be on the cutting edge of AI.
* Performance, scalability, cost -- cache a large percentage of AI calls and leverage the inherent parallelism built into {astra_db}.
* Enterprise governance and compliance - backed with enterprise support and SLAs, and offering support for HIPAA, TRUSTe, and SOC2 when running in Astra DB.
// [.landing-card-body-icon]
// image::what-is-astra-db.svg[Astra DB card icon,40]
--
****

++++
</div>
++++

[sidebar.landing-card]
.Get started
****
--
* xref:quickstart.adoc[]: Get up and running with RAGStack in minutes.
* xref:examples:index.adoc[]: Run Colab notebooks to see RAGStack in action.
* xref:intro-to-rag:index.adoc[]: Learn about the components of the RAG pattern and how they work together.
--
// [.landing-card-body-icon]
// image::what-is-astra-db.svg[Astra DB card icon,40]
****
