= {ragstack}

{ragstack} is a curated stack of the best open-source software for easing implementation of the RAG pattern in production-ready applications.

Instead of managing forks and installing dozens of open-source packages while wondering if you chose the right vector database solution, a single command (`brew install datastax/ragstack/ragstack`) unlocks all the open source packages required to build production-ready RAG applications.

== Components

DataStax has been busy helping our customers through the pains of RAG implementation, so the {ragstack} components we've selected have withstood production workloads and stringent testing by our engineering teams for performance, compatibility, and security.

* {ragstack} leverages the https://python.langchain.com/docs/get_started/introduction[LangChain^]{external-link-icon} ecosystem and is fully compatible with https://docs.smith.langchain.com/[LangSmith^]{external-link-icon} (for monitoring) and https://github.com/langchain-ai/langserve[LangServe^]{external-link-icon} (for hosting).

* The https://docs.datastax.com/en/astra-serverless/docs/[AstraDB] vector database provides the best performance and scalability for RAG applications, in addition to being particularly well-suited to RAG workloads like question answering, semantic search, and semantic caching.

* The https://langstream.ai[LangStream^]{external-link-icon} package combines the best of event-based architectures with the latest Gen AI technologies. Develop robust Gen AI pipelines with just YAML files. Leverage Kafka for data flow, and Kubernetes for deployment and scaling.

== Why {ragstack}?

{ragstack} offers solutions for challenges facing developers building RAG applications.

* Productivity - abstract over the RAG pattern's complexities to keep developers focused on business logic.
* Performance, scalability, cost - cache a large percentage of AI calls and leverage the inherent parallelism built into AstraDB
* Event-driven architectures - fresher data faster
* Advanced RAG techniques - use advanced patterns like Chain of Thought and Multi-Query RAG
* Future-proof - as new techniques are discovered, {ragstack} offers enterprise users an upgrade path to always be on the cutting edge of AI.

== What's next?

xref:quickstart.adoc[]