= {company} Luna for RAGStack

A subscription to {company} Luna for RAGStack gives you direct access to {company} Retrieval-Augmented Generation (RAG) in GenAI *support expertise*.

== Advantages of Luna for RAGStack

RAGStack is an out of the box solution simplifying RAG in GenAI apps. RAGStack includes an open-source RAG implementation, giving you a comprehensive GenAI Stack that leverages xref:examples:index.adoc#langchain-astraLangChain, xref:examples:index.adoc#llama-astraLlamaIndex, and more -- with expert support from {company}.

Adding an open-source component to a GenAI platform -- that supports experimentation and production environments -- can be complex. With Luna for RAGStack, you can confidently implement your own GenAI platform, and deploy the RAGStack open-source framework into production, with the peace of mind that comes from having direct access to experts.

See the https://www.datastax.com/blog/datastax-luna-provides-enterprise-grade-support-most-reliable-elastic-and-fastest[Luna blog] to learn more. 
(TODO: update link with Luna for RAGSTack blog when it is ready.)

== Luna for RAGSTack subscription pricing

For details about the subscription options and pricing, see the https://www.datastax.com/products/luna[Luna packages] page.  
(TODO: this URL depends on the addition of Luna for RAGStack pricing info.)

== Luna for RAGStack documentation

For more information, see the https://docs.datastax.com/en/luna-ragstack/docs/index.html[Luna for RAGStack] documentation.
(TODO: this URL will 404 until we publish on the launch date.)
