= Luna for RAGStack
:keywords: Luna, support, expertise, RAGStack, GenAI, Retrieval-Augmented Generation, RAG

Luna is a subscription to support and expertise at DataStax. It allows you to enjoy all the benefits of the components we support, with the peace of mind knowing you have direct access to the team that authors the majority of the code and supports some of the world's largest deployments. 

Adding external components to a GenAI platform to support development and production environments is complex. https://www.datastax.com/products/luna-ragstack[Luna for RAGStack] gives you direct access to experts who specialize in Retrieval-Augmented Generation (RAG) applications. 

RAGStack includes a RAG implementation, giving you a comprehensive GenAI stack that leverages xref:examples:index.adoc#langchain-astra[LangChain and Astra DB Serverless], xref:examples:index.adoc#llama-astra[LlamaIndex and Astra DB Serverless], and more. RAGStack supports integration with Vertex AI, Gemini, Bedrock, and NVIDIA NeMo embedding microservices, offering a wider array of tested, compatible embeddings and models for your applications.

To learn more, see the http://www.datastax.com/blog/empowering-enterprise-genai-announcing-luna-for-ragstack[Luna blog].

== Luna for RAGSTack subscription pricing

Please https://www.datastax.com/contact-us[contact us^] for details about the Luna for RAGStack subscription options and pricing.

// TODO: update the pricing URL when it's ready just before the launch date.
// See the https://www.datastax.com/products/luna[Luna packages] page.  

== What's next?

Get started with RAGStack by reading the xref:ROOT:quickstart.adoc[Quickstart]. Then see our extensive set of xref:examples:index.adoc[RAGStack examples].
