= Luna for RAGStack
:keywords: Luna, support, expertise, RAGStack, GenAI, Retrieval-Augmented Generation, RAG

// TODO: Hold until official announcement.

Luna is a subscription service that provides expert support for users of {company} products.

Luna for RAGStack gives you direct access to experts who specialize in Retrieval-Augmented Generation (RAG) in GenAI applications.

RAGStack is an out-of-the-box solution simplifying RAG in GenAI apps. RAGStack includes a RAG implementation, giving you a comprehensive GenAI stack that leverages xref:examples:index.adoc#langchain-astra[
LangChain and Astra DB Serverless], xref:examples:index.adoc#llama-astra[LlamaIndex and Astra DB Serverless], and more.

Adding external components to a GenAI platform to support development and production environments is complex. With the *core RAGStack functionality* supported in Luna for RAGStack, you can confidently implement your own GenAI platform and deploy the RAGStack framework into production with the peace of mind that comes from having access to the {company} RAG experts.

// Update the blog URL when it's ready just before the launch date.
// To learn more, see the https://www.datastax.com/blog/datastax-luna-provides-enterprise-grade-support-most-reliable-elastic-and-fastest[Luna blog]. 

== Luna for RAGSTack subscription pricing

Please https://www.datastax.com/contact-us[contact us^] for details about the Luna for RAGStack subscription options and pricing.

// TODO: update the pricing URL when it's ready just before the launch date.
// See the https://www.datastax.com/products/luna[Luna packages] page.  

== What's next?

Get started with RAGStack by reading the xref:ROOT:quickstart.adoc[Quickstart]. Then see our extensive set of xref:examples:index.adoc[RAGStack examples].
