"""
This module defines abstract base classes for implementing storage mechanisms for text chunk
embeddings, specifically designed to work with ColBERT or similar embedding models.
"""

from abc import ABC, abstractmethod
from typing import List, Optional

from .chunks import EmbeddedChunk


class BaseVectorStore(ABC):
    """
    Abstract base class (ABC) for a storage system designed to hold vector representations of text chunks,
    typically generated by a ColBERT model or similar embedding model.

    This class defines the interface for storing and managing the embedded text chunks, supporting
    operations like adding new chunks to the store and deleting existing documents by their identifiers.
    """

    @abstractmethod
    def put_chunks(
        self, chunks: List[EmbeddedChunk], delete_existing: Optional[bool] = False
    ) -> None:
        """
        Stores a list of embedded text chunks in the vector store, with an option to delete existing
        entries before insertion.

        Parameters:
            chunks (List[EmbeddedChunk]): A list of `EmbeddedChunk` instances to be stored.
            delete_existing (Optional[bool]): If True, any existing chunks with the same doc_ids
                                               as those in the `chunks` list will be deleted before
                                               inserting the new ones. Defaults to False.
        """

    @abstractmethod
    def delete_chunks(self, doc_ids: List[str]) -> None:
        """
        Deletes chunks from the vector store based on their document id.

        Parameters:
            doc_ids (List[str]): A list of document identifiers specifying the chunks to be deleted.
        """
