name: Build and deploy API reference
description: Build and deploy API reference

inputs:
  ragstack-version:
    required: true
    description: "RAGStack version"
runs:
  using: "composite"
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Generate API reference
      shell: bash
      run: |
        set -e
        ./scripts/generate-api-reference.sh "${{ inputs.ragstack-version }}"
        mv dist/api_reference /tmp/api_reference
        git fetch origin
        git checkout gh-pages
        ls -la /tmp/api_reference/${{ inputs.ragstack-version }}/langchain
        mkdir -p api_reference/${{ inputs.ragstack-version }}
        mv /tmp/api_reference/${{ inputs.ragstack-version }}/langchain api_reference/${{ inputs.ragstack-version }}/langchain
        if [ -z "$(git status --porcelain)" ]; then
          echo "Git directory is clean, nothing changed"
          git status
          exit 0
        fi
        git add -A
        git commit -m "Update api reference"
        git pull --rebase origin gh-pages
        git push origin gh-pages
