= RAGStack x Langflow

https://docs.langflow.org[Langflow^] is a visual way to build, iterate, and deploy AI applications. Its intuitive interface allows for easy manipulation of AI building blocks, enabling developers to quickly prototype and turn their ideas into powerful, real-world solutions.

A single Langflow "flow" could contain multiple Langchain chat components, a Llama language model, an Astra vector store, and a Redis cache. You can build any AI flow you can think of with Langflow, but how can you be confident that these components are up-to-date and compatible with your project?

Using the `ragstack-ai-langflow` package solves this problem. It provides the intuitive flow building of Langflow, with components tested for compatibility, performance, and security with RAGStack.

== Install Langflow

. Install Langflow.
[source,bash]
----
pip install ragstack-ai-langflow
----
+
. Start Langflow.
+
[source,bash]
----
langflow run
----
+
. A browser window will open with the Langflow interface.
You can now access Langflow at `http://127.0.0.1:7860/`.

[source,bash]
----
Result:

│ Welcome to ⛓ Langflow                             │
│                                                   │
│ Access http://127.0.0.1:7860                      │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
----

. To create a new project, click **New Project**.
. Select **Blank Flow** to start with a blank canvas, or select one of the **Starter Projects** to try a pre-built flow.
We recommend the https://pre-release.langflow.org/starter-projects/basic-prompting[Basic Prompting] project to get started.

== The ragsstack-ai-langflow package

The `ragstack-ai-langflow` package includes the minimum set of dependencies for using https://docs.langflow.org/[Langflow] with Langchain, {astra_db}, and https://python.langchain.com/docs/integrations/platforms/google[Google Vertex AI and Google Gemini API].

This package includes Langflow with `ragstack-ai-langchain[google]` as a dependency.

LLMs, embeddings, and third-party providers are not included in this package by default, except for OpenAI, Azure OpenAI, and Google Vertex AI.

Additional LangChain packages should work out of the box, although you need to manage the packages and their dependencies yourself.


