= Langflow

https://docs.langflow.org[Langflow] is a visual way to build, iterate, and deploy AI applications. Its intuitive interface allows for easy manipulation of AI building blocks, enabling developers to quickly prototype and turn their ideas into powerful, real-world solutions.

A single Langflow "flow" could contain multiple Langchain chat components, a Llama language model, an Astra vector store, and a Redis cache. You can build any AI flow you can think of with Langflow, but how can you be confident that these components are up-to-date and compatible with your project?

Using the `ragstack-ai-langflow` package solves this problem. It provides the intuitive flow building of Langflow, with components tested for compatibility, performance, and security with RAGStack.

== Install Langflow

. Install the `ragstack-ai-langflow` package.
+
[source,bash]
----
pip install ragstack-ai-langflow
----
+
. Start Langflow.
+
[tabs]
======
Bash::
+
[source,python]
----
langflow run
----

Result::
+
[source,console]
----
│ Welcome to ⛓ Langflow                             │
│                                                   │
│ Access http://127.0.0.1:7860                      │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
----
======
+
A browser window will open with the Langflow interface.
+
You can now access Langflow at `http://127.0.0.1:7860/`.
+
. To create a new project, click **New Project**.
. Select **Blank Flow** to start with a blank canvas, or select one of the **Starter Projects** to try a pre-built flow.
We recommend the https://pre-release.langflow.org/starter-projects/basic-prompting[Basic Prompting] project to get started.

== The ragstack-ai-langflow package

The `ragstack-ai-langflow` package contains a curated set of dependencies for using https://docs.langflow.org/[Langflow] with {astra_db} and all the supported integrations by `ragstack-ai-langchain`.

All of Langflow's builtin integrations are included in the `ragstack-ai-langflow` package.