name: Setup Python
description: Setup Python and pip/tox/poetry

inputs:
  python-version:
    default: 3.11
    description: 'Astra DB application token'
runs:
  using: "composite"
  steps:
    - name: "Setup: Python ${{ inputs.python-version }}"
      uses: actions/setup-python@v5
      with:
        python-version: "${{ inputs.python-version }}"
        cache: "pip"

    - name: "Install tox"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox poetry