name: Setup Python
description: Setup Python and pip/tox/poetry

inputs:
  python-version:
    default: "3.11"
    description: 'Python version'
runs:
  using: "composite"
  steps:
    - name: "Setup: Python ${{ inputs.python-version }}"
      uses: actions/setup-python@v5
      with:
        python-version: "${{ inputs.python-version }}"
        cache: "pip"

    - name: "Install tox and poetry"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip uninstall -y tox poetry
        python -m pip install --upgrade tox>=4.11.1 poetry>=1.7.1
        tox --version
        poetry -V