name: 'Release package'
description: 'Build and release a package on PyPI'
inputs:
  package-directory:
    required: true
    description: 'Package directory'
  pypi-token:
    required: true
    description: 'PyPI token'
  pypi-test-token:
    required: true
    description: 'PyPI token'
  pypi-use-test-release:
    required: false
    default: "false"
    description: 'Whether to release to TestPyPI or PyPI'
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: 'Setup: Python 3.11'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install and build
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        cd ${{ inputs.package-directory }}
        poetry install --no-root
        poetry build

    - name: Compute PyPI Url
      id: pypi-url
      shell: bash
      run: |
          if [ "${{ inputs.pypi-use-test-release }}" == "true" ]; then
            echo "::set-output name=pypi-url::https://test.pypi.org/legacy/"
            echo "::set-output name=password::${{ inputs.pypi-test-token }}"
          else
            echo "::set-output name=pypi-url::https://pypi.org/legacy/"
            echo "::set-output name=password::${{ inputs.pypi-token }}"
          fi

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ inputs.package-directory }}/dist
        password: ${{ steps.pypi-url.outputs.password }}
        test-pypi: ${{ steps.pypi-url.outputs.pypi-url }}