name: "Release package"
description: "Build and release a package on PyPI"
inputs:
  package-directory:
    required: true
    description: "Package directory"
  pypi-token:
    required: true
    description: "PyPI token"
  pypi-test-token:
    required: true
    description: "PyPI token"
  pypi-use-test-release:
    required: false
    default: "false"
    description: "Whether to release to TestPyPI or PyPI"
runs:
  using: "composite"
  steps:
    - name: Install and build
      shell: bash
      run: |
        cd ${{ inputs.package-directory }}
        poetry install --no-root
        poetry build

    - name: Compute PyPI Url
      id: pypi-url
      shell: bash
      run: |
        if [ "${{ inputs.pypi-use-test-release }}" == "true" ]; then
          echo "pypi-url=https://test.pypi.org/legacy/" >> $GITHUB_OUTPUT
          echo "password=${{ inputs.pypi-test-token }}" >> $GITHUB_OUTPUT
        else
          echo "pypi-url=https://pypi.org/legacy/" >> $GITHUB_OUTPUT
          echo "password=${{ inputs.pypi-token }}" >> $GITHUB_OUTPUT
        fi

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ inputs.package-directory }}/dist
        password: ${{ steps.pypi-url.outputs.password }}
        test-pypi: ${{ steps.pypi-url.outputs.pypi-url }}
