name: Lint
description: runs linters

runs:
  using: composite
  steps:
    - name: Lint
      shell: bash
      run: |
        tox -e lint
        rm -rf .tox

    - name: Notebook
      shell: bash
      run: |
        python scripts/format-example-notebooks.py
        if [ -n "$(git status --porcelain)" ]; then
          echo "Notebooks are not formatted"
          echo "Please run 'python scripts/format-example-notebooks.py' and commit the changes."
          git status
          exit 1
        fi
