name: Lint
description: runs linters

runs:
  using: composite
  steps:
    - name: "Setup Python and Tox"
      uses: ./.github/actions/setup-python
    - name: Lint
      shell: bash
      run: |
        tox -e lint
