name: Astra DB Setup
description: Setup a new database in Astra DB

inputs:
  astra-token:
    required: true
    description: 'Astra DB application token'
  db-name:
    required: true
    description: 'Astra DB database name'
runs:
  using: "composite"
  steps:
  - name: Create a new database
    shell: bash
    env:
      TERM: linux
    run: |
      set -x
      (curl -Ls "https://dtsx.io/get-astra-cli" | bash) || true 
      /home/runner/.astra/cli/astra db create -v "${{ inputs.db-name }}" -k default_keyspace --token "${{ inputs.astra-token }}" --vector
      
      text=$(/home/runner/.astra/cli/astra describe "${{ inputs.db-name }}" --token "${{ inputs.astra-token }}")
      database_id=$(echo "$text" | grep 'id' | awk -F '|' '{print $3}' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      region=$(echo "$text" | grep 'Regions' | grep '\[0\]' | awk -F '|' '{print $3}' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      echo "Found database id: $database_id"
      echo "Found region: $region"

      db_endpoint="https://${database_id}-${region}.apps.astra.datastax.com"
      echo "Database endpoint: $db_endpoint"
      echo "::set-output name=db_endpoint::$db_endpoint"
      echo "::set-output name=db_id::$database_id"

