runtime:
  log:
    failure_level: warn
git:
  # ensure_git_suffix: false # Enable if necessary -- some git services don’t recognize the URL if it contains the .git extension.
  fetch_concurrency: 10

site:
  title: DataStax RAGStack Docs
  start_page: docs::index.adoc
  url: https://docs.datastax.com/en/ragstack

content:
  sources:
  - url: ../
    start_path: docs

antora:
  extensions:
  - '@antora/collector-extension'

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  - extensions/remote-include-processor.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  attributes:
    # BUILT-IN ATTRIBUTES
    allow-uri-read: '' # this has no effect in antora, but does help development in Intellij
    experimental: ''
    idprefix: ''
    idseparator: '-'
    # kroki-fetch-diagram: true
    # kroki-server-url:
    max-include-depth: 10
    page-toclevels: 2@
    sectlinks: ''
    page-pagination: ''
    tabs-sync-option: ''
    table-caption: false
    figure-caption: false
    xrefstyle: short
    # CUSTOM ATTRIBUTES
    company: 'DataStax'
    astra_db: 'Astra DB'
    astra_stream: 'Astra Streaming'
    astra_ui: 'Astra Portal'
    db-cassandra: 'Astra DB Serverless (Non-Vector)'
    db-vector: 'Astra DB Serverless (Vector)'
    db-serverless: 'Astra DB Serverless'
    support_url: 'https://support.datastax.com'
    glossary-url: 'https://docs.datastax.com/en/glossary/docs/index.html#'
    external-link-icon: '&#x2197;'

urls:
  # redirect_facility: httpd
  latest_version_segment_strategy: redirect:from
  latest_version_segment: 'latest'

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  # Bsys requires the output.dir in the site-publish playbook to be specifically
  # set to "~/work/<repo-name>/build/site". This is because bsys clones the
  # content source repo into "/work", and then looks for the Antora-generated
  # site in "build/site" within the repo directory when deploying/syncing.
  dir: 'build/site'
