[tool.poetry]
name = "ragstack-e2e-tests"
version = "0.1.0"
description = "RAGStack tests"
license = ""
authors = ["DataStax"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12,!=3.9.7"

[tool.poetry.group.test.dependencies]
pytest = "*"
black = "*"
ruff = "*"
google-cloud-aiplatform = "^1.36.4"
langchain-google-genai = "^0.0.4"
langchain-nvidia-ai-endpoints = "^0.0.1"
boto3 = "^1.29.6"
huggingface-hub = "^0.20.3"
azure-storage-blob = "^12.19.0"
pillow = "^10.2.0"
testcontainers = "^3.7.1"
python-dotenv = "^1.0.1"
trulens-eval = "^0.21.0"
nemoguardrails = "^0.8.0"

# From LangChain optional deps, needed by WebBaseLoader
beautifulsoup4 = "^4"
# we need this specific feature from cassio: https://github.com/CassioML/cassio/pull/128
cassio = "~0.1.4"

# Remove when langchain-astradb is part of ragstack-ai package
langchain-astradb = "0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 250

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
