# changes required for ragstack-ai latest tests

[tool.poetry.group.test.dependencies]
#remove from the ragstack-e2e-tests pyproject
ragstack-ai = ""

# remove the following from the root ragstack-ai pyproject
astrapy = ""
unstructured = ""
llama-index = ""
llama-parse = ""
langchain = ""
langchain-core = ""
langchain-community = ""
langchain-openai = ""
langchain-google-vertexai = ""

# update these to specific versions
cassio = "~0.1.4"
google-cloud-aiplatform = "^1.36.4"
