runtime:
  log:
    failure_level: warn
git:
  # ensure_git_suffix: false # Enable if necessary -- some git services don’t recognize the URL if it contains the .git extension.
  fetch_concurrency: 10

site:
  title: DataStax Docs
  start_page: ragstack::index.adoc
  robots: disallow

content:
  branches: main # Sources default to this branch if none are specified.
  sources:
  - url: ..
    start_path: docs
    branches: HEAD

antora:
  extensions:
  - '@antora/atlas-extension'
  - '@antora/collector-extension'
  - extensions/assets-processor.js
  - extensions/tailwind-processor.js
  - id: unlisted-pages
    enabled: true
    require: extensions/unlisted-pages-extension.js
    add_to_navigation: false
    unlisted_pages_heading: Orphans

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  - extensions/remote-include-processor.js
  - extensions/svg-macro.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  attributes:
    # BUILT-IN ATTRIBUTES
    # allow-uri-read: '' # Quality-of-life benefit for IntelliJ users. CAUTION: Opens the door to malicious code insertion - must remain disabled in prod build environment.
    # hide-uri-scheme: '' # Consider enabling this attribute to make raw http hyperlinks look cleaner.
    experimental: ''
    idprefix: ''
    idseparator: '-'
    # kroki-fetch-diagram: true
    # kroki-server-url:
    max-include-depth: 10
    page-toclevels: 2@
    sectlinks: ''
    tabs-sync-option: ''
    example-caption: false
    figure-caption: false
    table-caption: false
    xrefstyle: short
    # CUSTOM ATTRIBUTES
    company: 'DataStax'
    astra_db: 'Astra DB'
    astra_stream: 'Astra Streaming'
    astra_ui: 'Astra Portal'
    astra_cli: 'Astra CLI'
    astra-streaming-examples-repo: 'https://raw.githubusercontent.com/datastax/astra-streaming-examples/master'
    luna-streaming-examples-repo: 'https://raw.githubusercontent.com/datastaxdevs/luna-streaming-examples/main'
    support_url: 'https://support.datastax.com'
    glossary-url: 'https://docs.datastax.com/en/glossary/docs/index.html#'
    emoji-tada: "&#127881;"
    emoji-rocket: "&#128640;"
    emoji-smile: "&#128512"
    dse: 'DataStax Enterprise (DSE)'
    cassandra: 'Apache Cassandra(R)'
    classic: 'classic'
    classic_cap: 'Classic'
    serverless: 'serverless'
    serverless_cap: 'Serverless'
    # Antora Atlas
    primary-site-url: https://docs.datastax.com/en
    primary-site-manifest-url: https://docs.datastax.com/en/site-manifest.json

urls:
  latest_version_segment_strategy: redirect:from
  latest_version_segment: 'latest'

ui:
  bundle:
    url: https://github.com/riptano/docs-ui/releases/latest/download/ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # supplemental_files: supplemental-ui

output:
  dir: 'build/site'