name: "Build and deploy Docker image"
description: "Build and deploy Docker image"
inputs:
  github-token:
    required: true
    description: 'Github token'
  ragstack-version:
    required: true
    description: 'Ragstack version'
  dry-run:
    required: false
    default: "true"
    description: 'Whether to push the image or not'
runs:
  using: "composite"
  steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for testing
      uses: docker/build-push-action@v5
      with:
        # this is required for being able to get the images later
        load: true
        context: docker
        file: docker/Dockerfile
        platforms: linux/amd64
        build-args: |
          RAGSTACK_AI_VERSION=${{ inputs.ragstack-version }}
        tags: ghcr.io/datastax/ragstack-ai:test
        push: false

    - name: Test docker image
      shell: bash
      run: |
        set -e
        docker run --rm ghcr.io/datastax/ragstack-ai:test python -c "import langchain"

    - name: Build Docker image and deploy
      uses: docker/build-push-action@v5
      with:
        context: docker
        file: docker/Dockerfile
        # We can only build for the intersection of platforms supported by
        # QEMU and base python image, for now build only for
        # linux/amd64 and linux/arm64
        platforms: linux/amd64
        build-args: |
          RAGSTACK_AI_VERSION=${{ inputs.ragstack-version }}
        tags: ghcr.io/datastax/ragstack-ai:latest,ghcr.io/datastax/ragstack-ai:${{ inputs.ragstack-version }}
        push: false
