name: "Build and deploy Docker image"
description: "Build and deploy Docker image"
inputs:
  github-token:
    required: true
    description: 'Github token'
  ragstack-version:
    required: true
    description: 'Ragstack version'
  dry-run:
    required: false
    default: "true"
    description: 'Whether to push the image or not'
runs:
  using: "composite"
  steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: docker
        file: docker/Dockerfile
        # We can only build for the intersection of platforms supported by
        # QEMU and base python image, for now build only for
        # linux/amd64 and linux/arm64
        platforms: linux/amd64,linux/arm64
        build-args: |
          RAGSTACK_AI_VERSION=${{ inputs.ragstack-version }}
        tags: ghcr.io/datastax/ragstack-ai:latest
        push: false

    - name: Test and push Docker images
      shell: bash
      run: |
        set -e
        docker images
        image_name=ghcr.io/datastax/ragstack-ai
        full_image_name_with_latest=${image_name}:latest
        full_image_name_with_version=${image_name}:${{ inputs.ragstack-version }}
        docker run --rm $full_image_name_with_latest python -c "import langchain"
        
        if [[ "${{ inputs.dry-run }}" == "true" ]]; then
          echo "Dry run, would have pushed the followings images:"
          echo "${full_image_name_with_latest}"
          echo "${full_image_name_with_version}"
        else
          docker tag $full_image_name_with_latest $full_image_name_with_version
          docker push ${full_image_name_with_version}
          docker push ${full_image_name_with_latest}
        fi
