name: Build and deploy docker image

on:
  workflow_dispatch:
    inputs:
      ragstack-version:
        description: 'RAGStack version (must exists on PyPI)'
        required: true
      dry-run:
        description: 'Dry run (do not push the image)'
        default: true
        type: boolean

jobs:
  docker-build-deploy:
    name: Docker deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker
        uses: ./.github/actions/build-deploy-docker-image
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ragstack-version: "${{ github.event.inputs.ragstack-version }}"
          dry-run: "${{ github.event.inputs.dry-run }}"
