name: Release RAGStack Llama-Index package

on:
  workflow_dispatch:
    inputs:
      pypi-use-test-release:
        description: 'Whether to release to TestPyPI or PyPI'
        type: boolean
        required: true
        default: false

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: ./.github/actions/release-package
        with:
          package-directory: libs/ragstack-ai-llamaindex
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          pypi-test-token: ${{ secrets.PYPI_TEST_API_TOKEN }}
          pypi-use-test-release: ${{ github.event.inputs.pypi-use-test-release }}
