name: Release RAGStack package

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: .github/actions/release-package
        with:
          package-directory: "."
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          pypi-test-token: ${{ secrets.PYPI_TEST_API_TOKEN }}
          pypi-use-test-release: ${{ github.event.inputs.pypi-use-test-release }}
