name: Release RAGStack package

on:
  push:
    tags:
      - "ragstack-ai-*"

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release
        uses: ./.github/actions/release-package
        with:
          package-directory: "."
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          pypi-test-token: ${{ secrets.PYPI_TEST_API_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: false

