name: Scheduled tests (LangChain dev, LLamaIndex dev, RAGStack latest release)
on:
  workflow_dispatch: {}
  schedule:
    # astra dev and dse - every 2 hours
    - cron: '0 */2 * * *'
  pull_request:
    paths-ignore:
      - "scripts/**"
      - "docs/**"
      - "README.adoc"
      - "PACKAGE_README.md"
    branches:
      - main

concurrency:
  group: ragstack-ci-all-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compute-vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo ""
    outputs:
      astradb-dev-region: "us-west-2"
      astradb-dev-cloud: "aws"

  langchain-dse-tests:
    name: "LangChain dev / DSE"
    needs: ["compute-vars"]
    uses: ./.github/workflows/_run_e2e_tests.yml
    secrets: inherit
    with:
      suite-name: "langchain"
      astradb: false
      vector-database-type: "local-cassandra"
      deploy-to-slack: true
      slack-title: "LangChain dev / DSE"
      deploy-to-testspace: true
      testspace-space: "RAGStack test suite - LangChain dev - DSE"

  langchain-astradev-tests:
    name: "LangChain dev / AstraDB dev"
    needs: ["compute-vars"]
    if: ${{ contains(github.event.schedule, '0 */2 * * *') || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/_run_e2e_tests.yml
    secrets: inherit
    with:
      suite-name: "langchain"
      astradb: true
      astradb-token-secret-name: "E2E_TESTS_ASTRA_DEV_DB_TOKEN"
      astradb-env: "DEV"
      astradb-region: "${{ needs.compute-vars.outputs.astradb-dev-region }}"
      astradb-cloud: "${{ needs.compute-vars.outputs.astradb-dev-cloud }}"
      vector-database-type: "astradb"
      deploy-to-slack: true
      slack-title: "LangChain dev / AstraDB dev"
      deploy-to-testspace: true
      testspace-space: "RAGStack test suite - LangChain dev - AstraDB"

  llamaindex-dse-tests:
    name: "LLamaIndex dev / DSE"
    needs: ["compute-vars"]
    uses: ./.github/workflows/_run_e2e_tests.yml
    secrets: inherit
    with:
      suite-name: "llamaindex"
      astradb: false
      vector-database-type: "local-cassandra"
      deploy-to-slack: true
      slack-title: "LLamaIndex dev / DSE"
      deploy-to-testspace: true
      testspace-space: "RAGStack test suite - LLamaIndex dev - DSE"

  llamaindex-astradev-tests:
    name: "LLamaIndex dev / AstraDB dev"
    needs: ["compute-vars"]
    if: ${{ contains(github.event.schedule, '0 */2 * * *') || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/_run_e2e_tests.yml
    secrets: inherit
    with:
      suite-name: "llamaindex"
      astradb: true
      astradb-token-secret-name: "E2E_TESTS_ASTRA_DEV_DB_TOKEN"
      astradb-env: "DEV"
      astradb-region: "${{ needs.compute-vars.outputs.astradb-dev-region }}"
      astradb-cloud: "${{ needs.compute-vars.outputs.astradb-dev-cloud }}"
      vector-database-type: "astradb"
      deploy-to-slack: true
      slack-title: "LLamaIndex dev / AstraDB dev"
      deploy-to-testspace: true
      testspace-space: "RAGStack test suite - LLamaIndex dev - AstraDB"

  ragstack-latest-release-dse-tests:
    name: "RAGStack latest / DSE"
    needs: ["compute-vars"]
    uses: ./.github/workflows/_run_e2e_tests.yml
    secrets: inherit
    with:
      suite-name: "ragstack-latest-release"
      astradb: false
      vector-database-type: "local-cassandra"
      deploy-to-slack: true
      slack-title: "RAGStack latest / DSE"
      deploy-to-testspace: true
      testspace-space: "RAGStack test suite - RAGStack latest - DSE"

  ragstack-latest-release-astradev-tests:
    name: "RAGStack latest / AstraDB dev"
    needs: ["compute-vars"]
    if: ${{ contains(github.event.schedule, '0 */2 * * *') || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/_run_e2e_tests.yml
    secrets: inherit
    with:
      suite-name: "ragstack-latest-release"
      astradb: true
      astradb-token-secret-name: "E2E_TESTS_ASTRA_DEV_DB_TOKEN"
      astradb-env: "DEV"
      astradb-region: "${{ needs.compute-vars.outputs.astradb-dev-region }}"
      astradb-cloud: "${{ needs.compute-vars.outputs.astradb-dev-cloud }}"
      vector-database-type: "astradb"
      deploy-to-slack: true
      slack-title: "RAGStack latest / AstraDB dev"
      deploy-to-testspace: true
      testspace-space: "RAGStack test suite - RAGStack latest - AstraDB"