name: Release Test package

on:
  workflow_dispatch: {}

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_LANGCHAIN_SUBMODULE }}
            ${{ secrets.SSH_PRIVATE_KEY_LANGSERVE_SUBMODULE }}
            ${{ secrets.SSH_PRIVATE_KEY_LANGSMITH_SUBMODULE }}

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: 'Setup: Python 3.11'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Build package
        run: |
          poetry build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
