name: Update GitHub pages

on:
  workflow_dispatch:
    inputs:
      ragstack-version:
        description: 'RAGStack version (must exists on PyPI)'
        required: true

jobs:
  update-api-reference:
    name: Update API reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Update API reference
        uses: ./.github/actions/deploy-api-reference
        with:
          ragstack-version: ${{ github.event.inputs.ragstack-version }}
